# Generated by Django 2.2.1 on 2019-05-19 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='RName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Restaurant', to_field='RName'),
        ),
    ]
