# Generated by Django 2.2.1 on 2019-05-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190519_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(-1, '未起送'), (0, '正在配送'), (1, '已送达')], default=-1),
        ),
    ]
