# Generated by Django 2.2.1 on 2019-05-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20190519_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='end_time',
            field=models.TimeField(blank=True, max_length=100),
        ),
    ]
