# Generated by Django 2.2.1 on 2019-05-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190519_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['RName']},
        ),
        migrations.AlterModelOptions(
            name='rider',
            options={'ordering': ['AName']},
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='rider',
            name='rating',
        ),
        migrations.AddField(
            model_name='rider',
            name='fee',
            field=models.IntegerField(default=0),
        ),
    ]
