# Generated by Django 2.2.1 on 2019-05-19 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20190519_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='rating',
        ),
    ]
