# Generated by Django 2.2.1 on 2019-05-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_food_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='RImage',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_image'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='RName',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='RType',
            field=models.CharField(blank=True, choices=[('snack', '快餐'), ('japanese', '日料'), ('chinese', '中式料理'), ('western', '西餐'), ('dessert', '甜品')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='rider',
            name='fee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
