# Generated by Django 2.2.1 on 2019-05-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Rider'),
        ),
    ]
