# Generated by Django 2.2.1 on 2019-05-25 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('未起送', '未起送'), ('正在配送', '正在配送'), ('已送达', '已送达')], default='未起送', max_length=128),
        ),
    ]
